@startuml
class Agency {
    -String name
    -String address
    +getters e setters
}

class AgencyDTO {
    -String name
    -String address
}

class AgencyRepository {
    +save(Agency agency)
    +delete(Agency agency)
    +findByNameAndAddress(String name, String address) Agency
    +findAll() List<Agency>
}

class AgencyRepositoryImpl {
    +save(Agency agency)
    +delete(Agency agency)
    +findByNameAndAddress(String name, String address) Agency
    +findAll() List<Agency>
}

class AgencyService {
    +createAgency(AgencyDTO agencyDTO)
    +updateAgency(String oldName, String oldAddress, AgencyDTO agencyDTO)
    +deleteAgency(AgencyDTO agencyDTO)
    +getAgencyByNameAndAddress(String name, String address) Agency
}

AgencyService --> AgencyRepository
AgencyRepository <|.. AgencyRepositoryImpl

note "As agências devem ser únicas." as N1
Agency .. N1

note "AgencyService gerencia operações de agência." as N2
AgencyService .. N2

@enduml
