@startuml Locadora
    participant User
    participant RentalService
    participant VehicleService
    participant CustomerService
    participant AgencyService
    participant RentalDAO
    participant FileUtil

    User->>RentalService: rentVehicle(customerId, vehicleId, agencyId, startDate)
    RentalService->>CustomerService: getCustomer(customerId)
    CustomerService->>FileUtil: readFromFile("customers.txt")
    FileUtil-->>CustomerService: customerData
    CustomerService-->>RentalService: customer

    RentalService->>VehicleService: getVehicle(vehicleId)
    VehicleService->>FileUtil: readFromFile("vehicles.txt")
    FileUtil-->>VehicleService: vehicleData
    VehicleService-->>RentalService: vehicle

    RentalService->>AgencyService: getAgency(agencyId)
    AgencyService->>FileUtil: readFromFile("agencies.txt")
    FileUtil-->>AgencyService: agencyData
    AgencyService-->>RentalService: agency

    RentalService->>RentalService: createRental(customer, vehicle, agency, startDate)
    RentalService->>RentalDAO: save(rental)
    RentalDAO->>FileUtil: appendToFile("rentals.txt", rentalData)
    RentalService-->>User: rentalConfirmation
@enduml