@startuml

package "Entities" {
    class Vehicle {
        +getPlaca()
        +getModelo()
        +getMarca()
        +getAno()
        +isDisponivel()
        +getTipo()
        +getPrecoDiaria()
    }

    class VehicleDTO {
        +placa
        +modelo
        +marca
        +ano
        +disponivel
        +precoDiaria
        +getTipo()
    }

    class CarDTO {
        +metodoCarro()
    }

    class MotorcycleDTO {
        +metodoMoto()
    }

    class TruckDTO {
        +metodoCaminhao()
    }

    Vehicle <|-- VehicleDTO
    VehicleDTO <|-- CarDTO
    VehicleDTO <|-- MotorcycleDTO
    VehicleDTO <|-- TruckDTO
}

package "Services" {
    class VehicleService {
        +addVehicle(vehicleDTO: VehicleDTO)
        +getAllVehicles()
        +updateVehicle(vehicleDTO: VehicleDTO)
        +rentVehicle(vehicleDTO: VehicleDTO)
        +returnCar(vehicleDTO: VehicleDTO)
        +deleteVehicle(placa: String)
        +getVehicleByPlaca(placa: String)
        +searchVehicleByName(nome: String)
        +getVehiclesByPage(pageNumber: int, pageSize: int)
    }
}

package "Repositories" {
    interface VehicleRepository {
        +save(vehicleDTO: VehicleDTO)
        +findAll(): List<VehicleDTO>
        +update(updatedVehicleDTO: VehicleDTO)
        +delete(placa: String)
        +findByPlaca(placa: String): VehicleDTO
        +findByNome(nome: String): List<VehicleDTO>
    }

    class VehicleRepositoryImpl {
        +save(vehicleDTO: VehicleDTO)
        +findAll(): List<VehicleDTO>
        +update(updatedVehicleDTO: VehicleDTO)
        +delete(placa: String)
        +findByPlaca(placa: String): VehicleDTO
        +findByNome(nome: String): List<VehicleDTO>
    }
}

package "Utils" {
    class FileUtil {
        +logError(e: Exception)
        +serialize(objects: List<VehicleDTO>, fileName: String)
        +deserialize(fileName: String): List<VehicleDTO>
    }

    class Exception {
        +DuplicateEntityException
        +EntityNotFoundException
        +RentIllegalUpdateException
    }
}

VehicleService --> VehicleRepository
VehicleRepositoryImpl ..|> VehicleRepository
VehicleRepositoryImpl --> FileUtil

@enduml
